image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  before_script:
    - dotnet restore
  script:
    - dotnet build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - "artifacts/bin"
      - "artifacts/obj"
    expire_in: 20 minutes

test:
  stage: test
  image: philippheuer/docker-gitlab-powershell
  script:
    - powershell -File test.ps1
  dependencies:
    - build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - "artifacts/bin"
      - "artifacts/obj"
      - "artifacts/TestResults/"
    expire_in: 20 minutes
    
deploy:coverage:
  stage: deploy
  before_script:
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
  script:
    - ./codecov -f "./artifacts/TestResults/coverage.opencover.xml" -t $CODECOV_TOKEN
  dependencies:
    - test

deploy:
  stage: deploy
  script:
    - dotnet pack -c Release
  dependencies:
    - test
  when: manual
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - "artifacts/packages/Release/Shipping"
    expire_in: 1d
