pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: dotnet build
  displayName: 'build'
  
- bash: |
    dotnet tool install --global coverlet.console
    coverlet $(System.DefaultWorkingDirectory)/artifacts/bin/Fathcore.Tests/Debug/netcoreapp2.2/Fathcore.Tests.dll --target "dotnet" --targetargs "test --no-build" --exclude "[xunit*]*" --output $(System.DefaultWorkingDirectory)/artifacts/TestResults/ --format cobertura
  displayName: 'test with coverage'

- task: PublishCodeCoverageResults@1
  displayName: 'publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/artifacts/TestResults/coverage.cobertura.xml'
