pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: dotnet build
  displayName: 'build'

- script: dotnet tool install --global coverlet.console
- script: coverlet ./artifacts/bin/Fathcore.Tests/Debug/netcoreapp2.2/Fathcore.Tests.dll --target "dotnet" --targetargs "test --no-build" --exclude "[xunit*]*" --output ./artifacts/TestResults/ --format lcov --format opencover --format cobertura
- script: coverlet ./artifacts/bin/Fathcore.Extensions.Tests/Debug/netcoreapp2.2/Fathcore.Extensions.Tests.dll --target "dotnet" --targetargs "test --no-build" --exclude "[xunit*]*" --merge-with "./artifacts/TestResults/coverage.json" --output ./artifacts/TestResults/ --format lcov --format opencover --format cobertura
  displayName: 'test with coverage'

- task: PublishCodeCoverageResults@1
  displayName: 'publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/artifacts/TestResults/coverage.cobertura.xml'